### PR TITLE
Added "How To Play" button.

### PR DESCRIPTION
**Pull request by SNNR**
A question mark is added under the 'settings icon'.

By clicking the question mark the 'settings' modal will be hidden and only the "How To Play" modal will be visible. Messing around with it may cause neither modal to appear, but utilizing the PairPort title to reset the main menu will generally restore the "settings" modal.

When starting a new game, clicking the question mark will only show the "How To Play" modal while keeping the "settings" modal hidden until pressing the gear.

### CODE REVIEW

**Review by richardlara67 — COMMENTED** [review]
Very helpful new feature! 

My only concern is that having the settings icon and the "how-to" icon right next to each other makes it look too crowded. What do you think about moving the "how-to" icon on the top right corner instead?

**Comment by SNNR** [comment]
I'll see what I can do with the formatting. Now that I look at it the top right would be the best.

**Comment by SNNR** [comment]
I was able to adjust the how-to button to the top-right and added a close button to it. However, because it is no longer within the menu bar it will be unreachable underneath the "settings" modal until in-game where the modal is hidden.

**Comment by richardlara67** [comment]
Can you publish your new edits so I can take a look at it? I may be able to help.

**Comment by SNNR** [comment]
It's updated on my fork, it should be ready to look at.

**Comment by richardlara67** [comment]
Figured it out:

- Leave the "howto" where it was before (right next to settings icon).
- Make the following changes to the ID "pairport--howto-icon":
-Assign an **absolute** value to the **position** attribute.
-Give the ID a z-index a value higher than the class "modal" (3+).
-Adjust the position of the image using the **top** and **right** attributes

**Review by richardlara67 — APPROVED** [review]
Great job!

**Pull request merged**
